[workspace]
members = [
  "kindelia",
  "kindelia_common",
  "kindelia_lang",
  "kindelia_core",
  "kindelia_ws",
  "kindelia_server",
  "kindelia_client",
]

[profile.dev_fast]
inherits = "dev"
opt-level = 3
