[node.data]
dir = "~/.kindelia/state"
mine = false

[node.network]
network_id = "0xCAFE000000000003"
initial_peers = [
  "64.227.110.69",
  "188.166.3.140",
]

[node.api]
port = 8000

# # TODO
# [node.ws]
# port = 3000
