[node.data]
dir = "~/.kindelia/state"

[node.network]
network_id = "0xCAFE0006"

[node.networks.0xCAFE0006]
initial_peers = [
  "64.227.110.69",
  "188.166.3.140",
]

[node.mining]
enable = false

[node.api]
port = 8000

[node.ws]
buffer_size = 2048

